apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: {{ .Values.image }}
          name: worker
          command:
            - /usr/local/bin/worker
          args:
            - --groupID={{ .Values.kafka.groupID }}
          env:
            - name: KAFKA_GROUP_ID
              value: {{ .Values.kafka.groupID }}
            - name: KAFKA_TOPIC_NAME
              value: rentals
