controller:
  replicaCount: 1
  podAnnotations:
    sidecar.signadot.com/inject: "true"

listeners:
  client:
    protocol: PLAINTEXT

persistence:
  size: 1Gi

zookeeper:
  persistence:
    size: 1Gi
  podAnnotations:
    sidecar.signadot.com/inject: "true"

extraConfig: |
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1
  transaction.state.log.min.isr=1
  default.replication.factor=1
  min.insync.replicas=1
  auto.create.topics.enable=true
  offsets.topic.num.partitions=1

