on: [push]

jobs:
  preview:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_DEV_TOKEN }}
        url: https://okteto.nacho.dev.okteto.net/

    - name: Deploy Application
      uses: okteto/pipeline@master
      with:
        namespace: nacho

